class AppConstants:
    CODE_SUCCESS = 200
    CODE_CREATED = 201
    CODE_LOCKED = 423
    CODE_INVALID_REQUEST = 400
    CODE_UNAUTHORIZED = 401
    CODE_FORBIDDEN = 403
    DATA_NOT_FOUND = 404
    CODE_CONFLICT = 409
    CODE_RATE_LIMIT_EXCEEDED = 429
    CODE_INTERNAL_SERVER_ERROR = 500
    SERVICE_UNAVAILABLE = 503
    UNSUCCESSFULL_STATUS_CODE = 400 
    CODE_TOO_MANY_REQUESTS = 429

